# 项目配置
entfrm:
  # 名称
  name: entfrm开发平台
  # 版本
  version: 2.1.0
  # 文件上传路径
  profile: /Users/wangxiang/IdeaProjects/my/entfrm-boot-business/db
  # 获取ip地址开关
  addressSwitch: true
  # redis开关
  redisSwitch: true
  #en_US 英语  zh_CN 简体中文
  lang: zh_CN

# 开发环境配置
server:
  # 服务端口
  port: 8888
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200 初始化的线程数，默认值10
    threads:
      max: 200
      min-spare: 10

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    encoding: utf-8
  # 序列化
  jackson:
    time-zone: GMT+8
    serialization:
      # 返回时间戳
      write-dates-as-timestamps: true
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       max-file-size:  50MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    # host: localhos
    # 端口，默认为6379
    port: 6379
    # 密码
    # password:
    host: 127.0.0.1
    #password: springboot2.0
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # jdbc-url: jdbc:mysql://127.0.0.1:3306/entfrm-boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true
      # username: root
      # password: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/entfrm-boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true
      username: root
      password: root
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 500
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: entfrm
        login-password: 123456
      filter:
        stat:
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true

# MyBatis Plus
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*.xml
    - classpath:/META-INF/modeler-mybatis-mappings/*.xml
  typeAliasesPackage: com.entfrm.biz.**.entity
  global-config:
    # 不显示banner
    banner: false
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
  configuration:
    call-setters-on-nulls: true
  configuration-properties:
    prefix:
    boolValue: TRUE
    blobType: BLOB

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /cms/article/*,/system/datasource/save,/system/datasource/update,/toolkit/dataset/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/toolkit/*,/quartz/*,/activiti/*,/cms/*

# 日志配置
logging:
  level:
    com.entfrm: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
